# Generated by Django 3.1.2 on 2020-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20201001_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='caption',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
